services:
  postgres:
    image: postgres:17.0-alpine
    container_name: postgres
    env_file: $RECALL_PROJECT_PATH/config/postgres.env
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    volumes:
      - pgdata-volume:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres_user -d postgres_db"
      interval: 3s
      timeout: 3s
      start_period: 5s
      retries: 5
    restart: always

volumes:
  minio-volume:
    driver_opts:
      type: none
      o: bind
      device: $MINIO_VOLUME_PATH
  pgdata-volume:
    driver_opts:
      type: none
      o: bind
      device: $POSTGRES_VOLUME_PATH
