networks:
  library-dev:

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: library-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ELASTIC_API_PORT}:9200"
      - "${ELASTIC_CLASTER_PORT}:9300"
    volumes:
      - es-lib-volume:/usr/share/elasticsearch/data

  postgres:
    image: postgres:17.0-alpine
    container_name: library-postgres
    env_file: $PROJECT_PATH/config/postgres.env
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    volumes:
      - pgdata-lib-volume:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres_user -d postgres_db"
      interval: 3s
      timeout: 3s
      start_period: 5s
      retries: 5
    restart: always
    networks:
      - library-dev

  minio-setup:
    container_name: library-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    image: minio/mc:latest
    env_file:
      - $PROJECT_PATH/config/minio-server.env
      - $PROJECT_PATH/config/minio-client.env
    volumes:
      - minio-lib-volume:/data
      - $PROJECT_PATH/config/minio-setup.sh:/setup.sh
    entrypoint: bash /setup.sh
    restart: always
    networks:
      - library-dev

  minio:
    container_name: library-minio
    image: minio/minio:latest
    env_file:
      - $PROJECT_PATH/config/minio-server.env
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_BROWSER_PORT}:9001"
    volumes:
      - minio-lib-volume:/data
    command: server --console-address ":9001"
    healthcheck:
      test: "curl -f http://localhost:9000/minio/health/live"
      interval: 3s
      timeout: 5s
      start_period: 10s
      retries: 5
    restart: always
    networks:
      - library-dev

volumes:
  es-lib-volume:
    driver_opts:
      type: none
      o: bind
      device: $ELASTIC_VOLUME_PATH
  minio-lib-volume:
    driver_opts:
      type: none
      o: bind
      device: $MINIO_VOLUME_PATH
  pgdata-lib-volume:
    driver_opts:
      type: none
      o: bind
      device: $POSTGRES_VOLUME_PATH
